# Task 1: Data Cleaning and Preprocessing

## Mall Customer Segmentation Dataset

### Summary
The Mall Customer Segmentation dataset includes details like Customer ID, Age, Gender, Annual Income and Spending Score. By analysing this type of dataset helps in understanding customer behaviour, tastes and preferences which eventually support adopting effective marketing strategies.

### Data Loading and Intial Overview

In [ ]:
# Loading the Dataset
import numpy as np
import pandas as pd
df = pd.read_csv(r"C:\Users\DHANYA\Downloads\archive (5).zip")
print("Dataset is loaded successfully!")

Dataset is loaded successfully!

In [ ]:
df

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [ ]:
#  Display Column Information and Non-Null Counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

### Data Pre-processing

In [ ]:
# Checking missing values
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

#### Note
- So it is confirmed that the given dataset is free from missing values.

In [ ]:
# Droping Duplicate Values
df.drop_duplicates()

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [ ]:
# Checking duplicated values
df.duplicated().sum()

np.int64(0)

#### Note
- This means that the dataset is free from duplicates.

In [ ]:
# Checking Data Types
df.dtypes

CustomerID                 int64
Gender                    object
Age                        int64
Annual Income (k$)         int64
Spending Score (1-100)     int64
dtype: object

#### Note
- The dataset is clean with appropriate data types - numeric features for analysis and on categorical variable (Gender) for grouping.

### Export as CSV

In [ ]:
# Exporting Cleaned Dataset
df.to_csv("cleaned_mall_customer_segmentation_dataset.csv", index=False)
print("CSV file successfully exported!")

CSV file successfully exported!

## Short Summary of Task:1

#### In Task 1, I performed essential data cleaning steps to prepare the dataset for analysis:
- Verified that the dataset has **no missing values**.
- Confirmed that there are **no duplicate records**.
- Checked and validated **data types**, ensuring numeric features and one categorical variable (Gender) are correctly structured.
- Finally, I exported the **cleaned dataset**.